# Generated by Django 4.2.13 on 2024-05-08 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocuementReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clientid', models.CharField(max_length=20)),
                ('name', models.CharField(help_text='Enter the client name', max_length=200, unique=True)),
                ('docid', models.CharField(max_length=20)),
            ],
        ),
    ]
